# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'Free Trial(460ca580-77b4-41d1-ac4d-86761a4e4ec8)'
      subscriptionId: '460ca580-77b4-41d1-ac4d-86761a4e4ec8'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'sri-rg'
      location: 'Central India'
      templateLocation: 'URL of the file'
      csmFileLink: 'https://github.com/Srilakshmi1-lab/AzureDevOpsRepo/blob/main/storage.json'
      deploymentMode: 'Incremental'
